<a href="https://colab.research.google.com/github/yingzibu/ODE/blob/main/learn/eigenvalue_eigenvector_calculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
Ka = 0.5
k10 = 0.1
k12 = 0.3
k21 = 0.2
A = np.array([[-Ka, 0, 0],
              [Ka, -k10-k12, k21],
              [0, k12, -k21]])

In [3]:
print(A)

[[-0.5  0.   0. ]
 [ 0.5 -0.4  0.2]
 [ 0.   0.3 -0.2]]


In [4]:
eigenvalues, eigenvectors = np.linalg.eig(A)
eigenvalues

array([-0.03542487, -0.56457513, -0.5       ])

In [5]:
eigenvectors

array([[ 0.        ,  0.        ,  0.14002801],
       [ 0.48096517,  0.7721779 ,  0.70014004],
       [ 0.8767397 , -0.6354064 , -0.70014004]])

## Test whether $A\mathbf{v} = \lambda \mathbf{v}$

In [7]:
v2 = eigenvectors[:, 2]
v2

array([ 0.14002801,  0.70014004, -0.70014004])

In [8]:
print(np.dot(A, v2))

[-0.070014   -0.35007002  0.35007002]


In [9]:
print(eigenvalues[2]*v2)

[-0.070014   -0.35007002  0.35007002]
